apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: rocha
  labels:
    app: mysql
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      tier: database
      
  template:
    metadata:
      labels:
        app: mysql
        tier: database
    spec:
      containers:
        - name: mysql
          image: mysql:5.7  # You can change the MySQL version if needed
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom :
                secretKeyRef :
                  name : mysql-secrets
                  key :  password
            - name: MYSQL_DATABASE # Setting Database Name from a 'ConfigMap'
              valueFrom :
                configMapKeyRef :
                  name : db-config
                  key :  dbName  
          ports:
            - containerPort: 3306  # MySQL default port



            # kubectl get pods -n rocha -o custom-columns="POD_IP:.status.podIP"

